// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK5ImO-cvNJJxTOL8Uc4H-88rAHvCVeKc',
    appId: '1:795601718124:web:d79c18d938fbb406b64149',
    messagingSenderId: '795601718124',
    projectId: 'cau-capstone-dm',
    authDomain: 'cau-capstone-dm.firebaseapp.com',
    storageBucket: 'cau-capstone-dm.appspot.com',
    measurementId: 'G-WNKPYXEEVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC71A9H9cV9y20h41rZFcqQ7r-hQB6DVMI',
    appId: '1:795601718124:android:780fbf42d27c9e31b64149',
    messagingSenderId: '795601718124',
    projectId: 'cau-capstone-dm',
    storageBucket: 'cau-capstone-dm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrEdnwC23yTJXzlFzcc3UtShf7OyUDhsA',
    appId: '1:795601718124:ios:4a4bf5384d3656d2b64149',
    messagingSenderId: '795601718124',
    projectId: 'cau-capstone-dm',
    storageBucket: 'cau-capstone-dm.appspot.com',
    iosClientId:
        '795601718124-ruf5s18uagvmufds4idfmht94ad2pjke.apps.googleusercontent.com',
    iosBundleId: 'com.example.highAloneStartup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrEdnwC23yTJXzlFzcc3UtShf7OyUDhsA',
    appId: '1:795601718124:ios:4a4bf5384d3656d2b64149',
    messagingSenderId: '795601718124',
    projectId: 'cau-capstone-dm',
    storageBucket: 'cau-capstone-dm.appspot.com',
    iosClientId:
        '795601718124-ruf5s18uagvmufds4idfmht94ad2pjke.apps.googleusercontent.com',
    iosBundleId: 'com.example.highAloneStartup',
  );
}
